export const BOOKMARK_REPO = 'BOOKMARK_REPO';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
export const SELECT_REPO = 'SELECT_REPO';
export const REQUEST_PAGE = 'REQUEST_PAGE';
export const RECEIVE_PAGE = 'RECEIVE_PAGE';
